# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: >
          ./mvnw clean verify
          sonar:sonar
          -Pcoverage
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=amrsamii
          -Dsonar.projectKey=amrsamii_Kotlin-GitHub-actions
          -Dsonar.scm.disabled=True
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
